### ISSUE TITLE
Please make filters() method protected

### ISSUE THREAD

**Issue by rtconner** [Kyslik/laravel-filterable#13]
Can you please make filters method protected. I would like to override it in my code.

... either that or provide another way for me to modify how this library reads the request object.
Currently it forces use of $this->request->only

**Comment by Kyslik** [comment]
@rtconner yea, will look in to it.

**Comment by Kyslik** [comment]
@rtconner I can not really change the visibility of `filters()` method; tests do fail if it's done. I think you can just override `applyFilters()` and not use `$this->filters()` at all.

Can you elaborate on `$this->request->only`, what else would you use in this scenario? It needs to check each and every field one by one. Every suggestion counts.
