### ISSUE TITLE
Filter based on many to many?

### ISSUE THREAD

**Issue by dambridge** [Kyslik/laravel-filterable#8]
Apologies if this isn't a proper issue. I have roles associated with my users through a hasMany relationship -- is it possible to filter based on an associated role? Do I need to construct a join query myself in my user filter?

**Comment by Kyslik** [comment]
No need to apologize :)

---

You may use [custom filters](https://github.com/Kyslik/laravel-filterable#example-with-custom-filters), which allows you to manipulate `builder` instance however you want, its available under `$this->builder`, which you are supposed to return. Other than that you can not do anything related to M-M relationship out of the box.

Good luck!
